name: weekplanner
description: WeekPlanner for GIRAF

version: 1.3.1
publish_to: none

module:
  androidX: true

environment:
  sdk: ">=3.5.0"
dependencies:
  audioplayers: ^1.2.0
  auto_size_text: ^3.0.0
  connectivity: ^3.0.6
  csv: ^5.1.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.2.6
  http: ^0.13.6
  path: ^1.9.0
  path_provider: ^2.1.4
  image: ^3.3.0
  image_picker: ^0.8.9
  injector: ^2.0.0
  internet_connection_checker: ^1.0.0
  material_design_icons_flutter: ^6.0.7296
  mutex: ^3.1.0
  quiver: ^3.2.1
  rflutter_alert: ^2.0.7
  rxdart: ^0.28.0
  shared_preferences: ^2.3.1
  sqflite: ^2.3.3
  sqflite_common: ^2.5.4
  sqflite_common_ffi: ^2.3.3
  tuple: ^2.0.2
  uuid: ^3.0.7

dev_dependencies:
  async_test:
    git:
      url: https://github.com/aau-giraf/async_test
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  assets:
    - assets/
    - assets/audio/
    - assets/icons/
    - assets/timer/
    - .env
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: "Quicksand"
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
